Repository lbl-anp/becquerel, pull requests merged in 2021-03, with the labels that each got.

#238 improve peak amplitude guess for gauss, gausserf, expgauss
  becquerel/core/fitting.py
Labels: effort-low, enhancement

#239 plot the fit evaluation error bands, and ensure fit is shown above other lines
  becquerel/core/fitting.py
Labels: effort-low, enhancement

#242 GitHub actions, black format, drop python2
  .github/workflows/pip_build_test.yaml
  .pylintrc
  .travis.yml
  CONTRIBUTING.md
  README.md
  becquerel/__init__.py
  becquerel/core/autocal.py
  becquerel/core/energycal.py
  becquerel/core/fitting.py
  becquerel/core/peakfinder.py
  becquerel/core/plotting.py
  becquerel/core/rebin.py
  becquerel/core/spectrum.py
  becquerel/core/utils.py
  becquerel/parsers/cnf_file.py
  becquerel/parsers/spc_file.py
  becquerel/parsers/spe_file.py
  becquerel/parsers/spectrum_file.py
  becquerel/tools/__init__.py
  becquerel/tools/df_cache.py
  becquerel/tools/element.py
  becquerel/tools/isotope.py
  becquerel/tools/isotope_qty.py
  becquerel/tools/materials.py
  becquerel/tools/nndc.py
  becquerel/tools/wallet_cache.py
  becquerel/tools/xcom.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  setup.cfg
  setup.py
  tests/autocal_test.py
  tests/df_cache_test.py
  tests/element_test.py
  tests/energycal_test.py
  tests/fitting_test.py
  tests/isotope_qty_test.py
  tests/isotope_test.py
  tests/materials_test.py
  tests/nndc_test.py
  tests/parsers_test.py
  tests/plotting_test.py
  tests/rebin_test.py
  tests/spectrum_test.py
  tests/wallet_cache_test.py
  tests/xcom_test.py
Labels: discuss, effort-high, priority

#254 Fix FWHM formula used by `PeakFilter`
  becquerel/core/peakfinder.py
  examples/autocal.ipynb
  tests/autocal_test.py
Labels: bug

#252 Constant min 0
  becquerel/core/fitting.py
Labels: effort-low
