Repository lbl-anp/becquerel, pull requests merged in 2021-04, with the labels that each got.

#250 Add plot method to EnergyCalBase
  becquerel/core/energycal.py
  examples/energycal.ipynb
Labels: effort-low, enhancement

#246 Github action for coveralls, readme badges, metadata refactor
  .github/workflows/coveralls.yaml
  .github/workflows/tests.yaml
  .gitignore
  COPYRIGHT.txt
  LICENSE.txt
  README.md
  becquerel/__init__.py
  becquerel/__metadata__.py
  requirements-dev.txt
  setup.cfg
  setup.py
  tests/autocal_test.py
  tests/metadata_test.py
  tests/rebin_test.py
  tests/utils.py
Labels: new feature, testing

#269 Run actions on schedule (nightly) and manually
  .github/workflows/coveralls.yaml
  .github/workflows/tests.yaml
Labels: testing
