Repository lbl-anp/becquerel, pull requests merged in 2021-02, with the labels that each got.

#146 Feature fitting #50
  becquerel/__init__.py
  becquerel/core/fitting.py
  examples/fitting.ipynb
  requirements.txt
  tests/fitting_test.py
Labels: new module, priority

#224 Auto label plot axes in fitting module #218
  becquerel/core/fitting.py
  becquerel/core/plotting.py
  becquerel/core/spectrum.py
Labels: effort-med, enhancement

#237 add specific_activity prop to bq.Isotope
  becquerel/tools/isotope.py
Labels: effort-low, enhancement
